board: 6 Pack
name: 6 StepStick XYZABC

# Stepper motor math:
# Stepper motor @ 200 steps/rev
# X, Y, Z, A, B, C motor @ 1/16 microstepping
# 1 step = 1.8 degrees on motor shaft
# Gear reduction: 20:1
# 1 step = 0.09 degrees on output shaft
# Steps/rev = 200 * 16 * 20 = 64000 steps/rev
# Steps/degree = 64000 / 360 = 177.77 steps/degree on output shaft

start:
  must_home: false

stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 5

axes:
  shared_stepper_disable_pin: gpio.4:high
  homing_runs: 2

  # Done
  x:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.2:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.32
        step_pin: gpio.33

  # Done
  y:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.15:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.25
        step_pin: gpio.26
  
  # Done
  z:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.36:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.27
        step_pin: gpio.14

  # Done
  a:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.39:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.12
        step_pin: gpio.13
  
  # Done
  b:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.34:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.23
        step_pin: gpio.22
  
  # Done
  c:
    steps_per_mm: 177.77
    max_rate_mm_per_min: 12000
    acceleration_mm_per_sec2: 800
    max_travel_mm: 120

    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: false

    motor0:
      limit_neg_pin: gpio.35:low
      pulloff_mm: 2
      stepstick:
        direction_pin: gpio.21
        step_pin: gpio.19